module.exports.codes = {
    UNAUTHORIZED: 403,
    SUCCESS: 200,

    ID_NOT_FOUND: 301,
    ID_NOT_FOUND_PUT_REQUEST: 301.1,
    ID_FOUND_POST_REQUEST: 302,
    ACCOUNT_LOCKED: 302.1,

    EMAIL_ALREADY_EXISTS: 305,
    CODE_ALREADY_EXISTS: 305.2,
    EMAIL_ALREADY_EXISTS_INACTIVE: 306,
    EMAIL_DOESNOT_EXIST: 307,
    EMAIL_SENDING_ERROR: 308,
    EMAIL_ALREADY_EXISTS_SOCIAL_AUTH: 309,
    EMAIL_NOT_ACTIVATED: 310,
    
    PHONE_ALREADY_EXISTS: 305.1,
    PHONE_ALREADY_EXISTS_INACTIVE: 306.1,
    PHONE_DOESNOT_EXIST: 307.1,
    PHONE_SENDING_ERROR: 308.1,
    

    HASH_DOESNOT_EXIST: 311,
    HASH_WRONG: 312,
    HASH_EXPIRED: 313,

    REWARD_POINTS: 320,

    PASSWORD_INCORRECT: 331,
    PASSWORD_WEAK: 332,
    PASSWORD_NOT_PROVIDED: 333,
    PASSWORD_NOT_MATCHED: 334,
    PASSWORD_RESET: 335,

    TOKEN_REFRESH_INCORRECT: 351,
    TOKEN_AUTH_EXPIRED: 352,
    TOKEN_AUTH_CORRUPTED: 353,
    TOKEN_CANNOT_VERIFY: 354,
    TOKEN_MISSING_VALUES: 355,

    FILE_NOT_FOUND: 361,
    FILE_READING_ERROR: 362,

    RECORD_NOT_FOUND: 371,
    
    URL_MALFORMED: 375,

    COULD_NOT_SEND_OTP: 381,
    OTP_EXPIRED: 382,
    OTP_INCORRECT: 384,
    OTP_ERROR: 383,

    INPUT_INVALID: 391,
    REQUEST_INVALID: 392,
    INVALID_RESPONSE: 393,
    ERROR_UPDATING_RAZOR_PAY_STATUS_PROCEDURE_JOB: 395,
    
    ERROR: 502,
    BULK_CREATE_ERROR: 502,


    RAZOR_PAY_GET_BY_ID: 431,


    SHARKCOPE_UNSUCCESSFULL: 441,
    SHARKCOPE_ERROR: 442,
    SHARKCOPE_NO_LOGIN: 443,
    SHARKCOPE_NO_CREDIT: 444,
    SHARKCOPE_MISSING_TAG: 445,
    SHARKCOPE_TOURNAMENT_NOT_FOUND: 446,


    AUTO_JOB_EVENTLOOP_PROCEDURE_ERROR_UPDATE_SHARKSCOPE_DATA: 451,
    AUTO_JOB_EVENTLOOP_PROCEDURE_ERROR_GET_EVENTS: 452,
    AUTO_JOB_EVENTLOOP_BULK_INSERT_ERROR: 453,
    AUTO_JOB_EVENTLOOP_PROCEDURE_ERROR_UPDATE_WINNING_DATA: 454,



    COUPON_NOT_FOUND: 461,
    OUT_OF_STOCK: 462,

    PRODUCT_NOT_FOUND: 463,

    REFUND_INVALID_ITEMS: 464,

    INVALID_FILE_TYPE: 465,

    VENDOR_CODE_NOT_EXISTS: 466,

    DEVICE_NOT_REGISTERED: 467,

    INVALID_ORIGIN_DOMAIN: 468,

    SUBSCRIPTION_ALREADY_EXIStS: 469,
    RAZOR_PAY_INVALID_AMOUNT: 470,
};


